#ifdef USE_VULKAN_BACKEND
#pragma once

#include <vector>
#include <cstddef>

extern "C" {

  extern const unsigned char _binary_conv2d_fp32_start[];
  extern const unsigned char _binary_conv2d_fp32_end[];

  extern const unsigned char _binary_conv2d_3x3_bn_fp32_start[];
  extern const unsigned char _binary_conv2d_3x3_bn_fp32_end[];

  extern const unsigned char _binary_conv2d_3x3_bn_relu_fp32_start[];
  extern const unsigned char _binary_conv2d_3x3_bn_relu_fp32_end[];

  extern const unsigned char _binary_conv2d_3x3_bn_mish_fp32_start[];
  extern const unsigned char _binary_conv2d_3x3_bn_mish_fp32_end[];

  extern const unsigned char _binary_conv2d_5x5_bn_fp32_start[];
  extern const unsigned char _binary_conv2d_5x5_bn_fp32_end[];

  extern const unsigned char _binary_conv2d_5x5_bn_relu_fp32_start[];
  extern const unsigned char _binary_conv2d_5x5_bn_relu_fp32_end[];

  extern const unsigned char _binary_conv2d_5x5_bn_mish_fp32_start[];
  extern const unsigned char _binary_conv2d_5x5_bn_mish_fp32_end[];

  extern const unsigned char _binary_add_pointwise_fp32_start[];
  extern const unsigned char _binary_add_pointwise_fp32_end[];

  extern const unsigned char _binary_matmul_fp32_start[];
  extern const unsigned char _binary_matmul_fp32_end[];

  extern const unsigned char _binary_matmul_tiled_chw_4x4x32_fp32_start[];
  extern const unsigned char _binary_matmul_tiled_chw_4x4x32_fp32_end[];

  extern const unsigned char _binary_bn_mask_fp32_start[];
  extern const unsigned char _binary_bn_mask_fp32_end[];

  extern const unsigned char _binary_bn_mask_relu_fp32_start[];
  extern const unsigned char _binary_bn_mask_relu_fp32_end[];

  extern const unsigned char _binary_bn_mask_mish_fp32_start[];
  extern const unsigned char _binary_bn_mask_mish_fp32_end[];

  extern const unsigned char _binary_global_pooling_channels_fp32_start[];
  extern const unsigned char _binary_global_pooling_channels_fp32_end[];

  extern const unsigned char _binary_sum_channels_fp32_start[];
  extern const unsigned char _binary_sum_channels_fp32_end[];

  extern const unsigned char _binary_add_channel_bias_nchw_fp32_start[];
  extern const unsigned char _binary_add_channel_bias_nchw_fp32_end[];

  extern const unsigned char _binary_add_channel_bias_nc_relu_fp32_start[];
  extern const unsigned char _binary_add_channel_bias_nc_relu_fp32_end[];

  extern const unsigned char _binary_add_channel_bias_nc_mish_fp32_start[];
  extern const unsigned char _binary_add_channel_bias_nc_mish_fp32_end[];

  extern const unsigned char _binary_extract_channel0_nchw_fp32_start[];
  extern const unsigned char _binary_extract_channel0_nchw_fp32_end[];

  extern const unsigned char _binary_value_head_pool_channels_fp32_start[];
  extern const unsigned char _binary_value_head_pool_channels_fp32_end[];
};

/**
 * @brief  this file will be generated by python script from spirv files before build
 * if no order of matrix given, it will be NCHW as default
 * template placeholder for now
 */
namespace VkSPIRVShaders {

  /**
   * @brief Direct convolution layer Fp32
   */
  extern const unsigned char* spirv_conv2d_fp32;
  extern size_t spirv_conv2d_fp32_size;

  /**
   * @brief Convolution layers 3x3 with identity activation function
   */
  extern const unsigned char* spirv_conv2d_3x3_bn_fp32;
  extern size_t spirv_conv2d_3x3_bn_fp32_size;
  /**
   * @brief Convolution layers 3x3 with ReLU activation function
   */
  extern const unsigned char* spirv_conv2d_3x3_bn_relu_fp32;
  extern size_t spirv_conv2d_3x3_bn_relu_fp32_size;

  /**
   * @brief Convolution layers 3x3 with Mish activation function
   */
  extern const unsigned char* spirv_conv2d_3x3_bn_mish_fp32;
  extern size_t spirv_conv2d_3x3_bn_mish_fp32_size;

  /**
   * @brief Convolution layers 5x5 with identity activation function
   */
  extern const unsigned char* spirv_conv2d_5x5_bn_fp32;
  extern size_t spirv_conv2d_5x5_bn_fp32_size;

  /**
   * @brief Convolution layers 5x5 with ReLU activation function
   */
  extern const unsigned char* spirv_conv2d_5x5_bn_relu_fp32;
  extern size_t spirv_conv2d_5x5_bn_relu_fp32_size;

  /**
   * @brief Convolution layers 5x5 with Mish activation function
   */
  extern const unsigned char* spirv_conv2d_5x5_bn_mish_fp32;
  extern size_t spirv_conv2d_5x5_bn_mish_fp32_size;

  /**
   * @brief Elemental wise add operation for skipping connections
   */
  extern const unsigned char* spirv_add_pointwise_fp32;
  extern size_t spirv_add_pointwise_fp32_size;

  /**
   * @brief Matmul operation, tiled matrix multiplication Fp32
   */
  extern const unsigned char* spirv_matmul_fp32;
  extern size_t spirv_matmul_fp32_size;

  /**
   * @brief Future support, NCHW matmul Fp32
   */
  // extern const unsigned char* spirv_matmul_tiled_chw_4x4x32_fp32;
  // extern size_t spirv_matmul_tiled_chw_4x4x32_fp32_size;

  /**
   * @brief Prediction phase BN shader fp32
   */
  extern const unsigned char* spirv_bn_mask_fp32;
  extern size_t spirv_bn_mask_fp32_size;

  /**
   * @brief Prediction phase BN + ReLU activation fused shader fp32
   */
  extern const unsigned char* spirv_bn_mask_relu_fp32;
  extern size_t spirv_bn_mask_relu_fp32_size;

  /**
   * @brief Prediction phase batch normalization, scale bias. Mish activation fused shader fp32
   */
  extern const unsigned char* spirv_bn_mask_mish_fp32;
  extern size_t spirv_bn_mask_mish_fp32_size;

  /**
   * @brief Sum of channels fp32
   */
  extern const unsigned char* spirv_sum_channels_fp32;
  extern size_t spirv_sum_channels_fp32_size;

  /**
   * @brief Global Pooling fp32
   */
  extern const unsigned char* spirv_global_pooling_channels_fp32;
  extern size_t spirv_global_pooling_channels_fp32_size;

  /**
   * @brief Value head pool channels fp32
   */
  extern const unsigned char* spirv_value_head_pool_channels_fp32;
  extern size_t spirv_value_head_pool_channels_fp32_size;

  /**
   * @brief Add channel bias NCHW fp32
   */
   extern const unsigned char* spirv_add_channel_bias_nchw_fp32;
   extern size_t spirv_add_channel_bias_nchw_fp32_size;

   /**
    * @brief Add channel bias NC with Relu activation fp32
    */
    extern const unsigned char* spirv_add_channel_bias_nc_relu_fp32;
    extern size_t spirv_add_channel_bias_nc_relu_fp32_size;

    /**
     * @brief Add channel bias NC with Mish activation fp32
     */
    extern const unsigned char* spirv_add_channel_bias_nc_mish_fp32;
    extern size_t spirv_add_channel_bias_nc_mish_fp32_size;

    /**
     * @brief Extract channel 0 from NCHW fp32
     */
    extern const unsigned char* spirv_extract_channel0_nchw_fp32;
    extern size_t spirv_extract_channel0_nchw_fp32_size;
}

#endif